### ISSUE TITLE
Doesn't work in 2018.3.

### ISSUE THREAD

**Issue by adshunt** [Itoen/ASE-LWRP#1]
Paths to Core.hlsl etc. all need updating, no problems there. But still hitting the following error:

Shader error in 'Custom/LightWeightSimpleLighting': undeclared identifier 'MainLightRealtimeShadowAttenuation' 

Any ideas?

**Comment by Itoen** [comment]
made a version for 18.3!

Get on [Release Page](https://github.com/Itoen/ASE-LWRP/releases)or[LWRP v4.0.0Higher Branch](https://github.com/Itoen/ASE-LWRP/tree/LWRPv4.0.0Higher?files=1):)

**Comment by adshunt** [comment]
Great!
